# You will need to replace (new_revision_id) with the actual ID generated by Alembic, but the content should be this.
"""Update check constraint on journal_entry_lines

Revision ID: 1a2b3c4d5e6f
Revises: d5a6759ef2f7
Create Date: 2025-06-18 19:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a2b3c4d5e6f' # Replace with your actual new revision ID
down_revision = 'd5a6759ef2f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted for correctness ###
    with op.batch_alter_table('journal_entry_lines', schema='sgpos') as batch_op:
        batch_op.drop_constraint('ck_journal_entry_lines_debit_or_credit_check', type_='check')
        batch_op.create_check_constraint(
            'debit_or_credit_check',
            "(debit_amount > 0 AND credit_amount = 0) OR (credit_amount > 0 AND debit_amount = 0)"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted for correctness ###
    with op.batch_alter_table('journal_entry_lines', schema='sgpos') as batch_op:
        batch_op.drop_constraint('debit_or_credit_check', type_='check')
        batch_op.create_check_constraint(
            'ck_journal_entry_lines_debit_or_credit_check',
            "(debit_amount >= 0 AND credit_amount >= 0) AND (debit_amount != credit_amount)"
        )

    # ### end Alembic commands ###
